#!/bin/bash

echo "${@}" >> /tmp/mcabber.log

TIMEOUT=0.10
BLINKS=10

led_on()  { xset led named "Scroll Lock" ; }
led_off() { xset -led named "Scroll Lock" ; }
lock()    { exec 200<$0 ; flock 200 || exit 1 ; }


if [ $1 = "MSG" ]; then
	case "$2" in
		IN)
			message="$(tac ~/.mcabber/histo/$3 | grep MR -B100 -m1 | tac | sed -r 's/MR \w+:\w+:\w+ \w+ //g')"
			notify-send "$3 :: $message"
			;;
		MUC)
			message="$(tac ~/.mcabber/histo/$3 | grep MR -B100 -m1 | tac | sed -r 's/MR \w+:\w+:\w+ \w+ //g')"
			notify-send "$3 :: $message"
			;;
		OUT)
			echo > /dev/null
			;;
    esac
fi

if [ "$1" == "UNREAD" ]; then
    if [ ${2%% *} -gt 0 ]; then
        lock
        for i in `seq 1 $BLINKS`; do
            led_on  ; sleep $TIMEOUT
            led_off ; sleep $TIMEOUT
        done
        led_on
    else
        lock
        led_off
    fi
fi
